server:
  port: 8881
spring:
  resources:
    static-locations: classpath:/template/,classpath:/static/
  mvc:
    view:
      suffix: .html
  datasource: # mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&autoR&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: # redis
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 32
        max-wait: -1 # 负数代表没有限制
        min-idle: 0
    timeout: 0
  #RabbitMQ
  rabbitmq:
    port: 5679
    host: localhost
    username:
    password:
    publisher-returns: true  # 开启returnedMessage回调 Exchange -> Queue
    publisher-confirm-type: correlated # 新版发布特性，默认none，correlated相当于开启confirms回调 P->Exchange
    listener:
      simple:
        acknowledge-mode: manual # 设置手动确认(ack) Queue -> C
        prefetch: 100
  mail:  # mail  password即授权码，username和from要一致
    host:
    username:
    password:
    from:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    com:
      whoamizq:
        rabbitmqmail:
          mapper: info